name: Project Deploy

on:
  push:
    branches:
    - "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Test
        run: npm test
        
      - name: Build Project
        run: npm run build
      
      - name: Deploy project
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build